Revert "Rename the deprecated lint clippy to clippy::all"
This reverts commit 7c10330cc3c09f12cbd5f21f8a224bc2230aab50.

The code did not compile with this commit. Reverting.

error[E0658]: scoped lint `clippy::all` is experimental (see issue #44690)
 --> gu-net/src/proto/wire.rs:8:10
  |
8 | #![allow(clippy::all)]
  |          ^^^^^^^^^^^